version: "3.7"

services:
 
  # citusdb:
  #   image: citusdata/citus
  #   container_name: postgresql
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - ntech

  postgresql:
    image: postgres:11-alpine
    container_name: postgresql
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ntech

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - ntech

  elasticsearch:
    image: elasticsearch:7.6.2
    volumes:
      - elasticseach-data:/usr/share/elasticsearch/data
    networks:
      - ntech

  redis:
    image: redis
    volumes:
      - redis-data:/data
    networks:
      - ntech

  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    volumes:
      - sqlserver-data
    networks:
      - ntech

volumes:
  postgres-data:
  sqlserver-data:
  seq-data:
  elasticseach-data:
  redis-data:

networks:
  ntech:
    name: ntech-network